apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-url-shortener-svc
  name: fastapi-url-shortener-svc
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: fastapi-url-shortener
  type: LoadBalancer
status:
  loadBalancer: {}
